# Final Exam
## [Quantum Computer Programming](https://fagonzalezo.github.io/qcp-2020-2/)



In [1]:
#TEST_CELL don't remove this comment
!pip install qiskit
!pip install pylatexenc
!pip install git+https://github.com/qiskit-community/qiskit-textbook.git#subdirectory=qiskit-textbook-src

     |████████████████████████████████| 8.5MB 8.7MB/s 
     |████████████████████████████████| 17.6MB 253kB/s 
     |████████████████████████████████| 204kB 43.5MB/s 
     |████████████████████████████████| 204kB 48.6MB/s 
     |████████████████████████████████| 2.1MB 38.8MB/s 
     |████████████████████████████████| 51kB 5.9MB/s 
     |████████████████████████████████| 5.9MB 39.0MB/s 
     |████████████████████████████████| 1.3MB 61.5MB/s 
     |████████████████████████████████| 194kB 35.0MB/s 
     |████████████████████████████████| 81kB 9.0MB/s 
     |████████████████████████████████| 614kB 46.7MB/s 
     |████████████████████████████████| 102kB 10.7MB/s 
     |████████████████████████████████| 2.6MB 43.7MB/s 
     |████████████████████████████████| 5.5MB 30.3MB/s 
  Created wheel for qiskit: filename=qiskit-0.23.1-cp36-none-any.whl size=2872 sha256=83614831a775c6d197217aa5b0ab0e73f2064804920c048e6b8ffea8fe0d5d37
  Stored in directory: /root/.cache/pip/wheels/92/b4/ac/d4b00806d1b413

In [2]:
from qiskit import QuantumCircuit, Aer, execute
from qiskit.circuit.library import HGate, RXGate, RYGate, RZGate
import numpy as np


## 1. (1.0)

Write a function that returns a circuit, that only uses the $R_y$ and $R_z$ gates, that behaves as the $H$ gate (ignoring any global phase). The maximum circuit depth is 3.

In [60]:
def circuit_1():
    qc = QuantumCircuit(1)
    qc.rz(np.pi, 0)
    qc.ry(np.pi / 2, 0)
    return qc 

Use the following cell to test your solution. Notice that the `np.allclose()` instruction is comparing using a $-i$ global phase. Your solution could have a different global phase.

In [61]:
#TEST_CELL don't remove this comment
qc = circuit_1()
unitary_backend = Aer.get_backend('unitary_simulator')
unitary = execute(qc,unitary_backend).result().get_unitary()
print(repr(unitary))
H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
np.allclose(unitary, -1j * H)

array([[ 4.32978028e-17-0.70710678j, -4.32978028e-17-0.70710678j],
       [ 4.32978028e-17-0.70710678j,  4.32978028e-17+0.70710678j]])


True

## 2. (1.5)

Write a function that returns a circuit, that only uses the $R_x$ and $R_z$ gates, that behaves as the $H$ gate (ignoring any global phase). The maximum circuit depth is 7.

In [16]:
def circuit_2():
    qc = QuantumCircuit(1)
    theta = np.pi / 2
    qc.rz(theta, 0) 
    qc.rx(theta, 0) 
    qc.rz(theta, 0)
    ### your code here
    return qc 

Use the following cell to test your solution. Notice that the `np.allclose()` instruction is comparing using a $-i$ global phase. Your solution could have a different global phase.

In [17]:
#TEST_CELL don't remove this comment
qc = circuit_2()
unitary_backend = Aer.get_backend('unitary_simulator')
unitary = execute(qc,unitary_backend).result().get_unitary()
print(repr(unitary))
H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
np.allclose(unitary, -1j * H)

array([[1.11022302e-16-0.70710678j, 0.00000000e+00-0.70710678j],
       [0.00000000e+00-0.70710678j, 1.11022302e-16+0.70710678j]])


True

## 3. (1.5)
Write a function that returns a circuit, that only uses the $RXRZ$  gate (defined below), that behaves as the  $H$  gate (ignoring any global phase). 

In [18]:
# DO NOT MODIFY THIS FUNCTION
def RXRZ_gate(psi):
    qc = QuantumCircuit(1, name="RXRZ")
    qc.rx(psi,0)
    qc.rz(psi,0)
    gate = qc.to_instruction()
    return gate


The following cell shows how to use the RXRZ gate in a circuit. The gate takes a parameter that specifies a rotation angle $\psi$. The examples uses $\psi = \pi$, but you can use whatever angle you want:

In [19]:
#TEST_CELL don't remove this comment
# How to use the RXRZ gate:
qc = QuantumCircuit(1)
qc.append(RXRZ_gate(np.pi), [0])
unitary_backend = Aer.get_backend('unitary_simulator')
unitary = execute(qc,unitary_backend).result().get_unitary()
print(repr(unitary))

array([[ 3.74939946e-33-6.123234e-17j, -1.00000000e+00-6.123234e-17j],
       [ 1.00000000e+00-6.123234e-17j,  3.74939946e-33+6.123234e-17j]])


In [56]:
def circuit_3():
    qc = QuantumCircuit(1)
    theta = np.pi / np.sqrt(2)
    n = 100
    for i in range(n):
      qc.append(RXRZ_gate(theta / n), [0])
    return qc 

Use the following cell to test your solution. Notice that the `np.allclose()` instruction is comparing using a $-i$ global phase. Your solution could have a different global phase. Also notice that the `np.allclose()` is called with an additional parameter `atol` to specify a greater tolerance ($0.01$) than the one used for the previous questions.

In [57]:
#TEST_CELL don't remove this comment
qc = circuit_3()
unitary_backend = Aer.get_backend('unitary_simulator')
unitary = execute(qc,unitary_backend).result().get_unitary()
print(repr(unitary))
H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
np.allclose(unitary, -1j * H, atol=0.01)

array([[ 1.61494511e-05-0.70708497j, -7.85406238e-03-0.70708497j],
       [ 7.85406238e-03-0.70708497j,  1.61494511e-05+0.70708497j]])


True

## 4. (1.0)
Write a function that receives a Simon's oracle circuit and determines the value of $b$. $b$ will be exactly 4 bits long and is represented as a string of length 4.

In [64]:
# DO NOT MODIFY THIS FUNCTION
# Taken from qiskit-textbook project
def simon_oracle(b):
    """returns a Simon oracle for bitstring b"""
    b = b[::-1] # reverse b for easy iteration
    n = len(b)
    qc = QuantumCircuit(n*2)
    # Do copy; |x>|0> -> |x>|x>
    for q in range(n):
        qc.cx(q, q+n)
    if '1' not in b: 
        return qc  # 1:1 mapping, so just exit
    i = b.find('1') # index of first non-zero bit in b
    # Do |x> -> |s.x> on condition that q_i is 1
    for q in range(n):
        if b[q] == '1':
            qc.cx(i, (q)+n)
    return qc 

In [158]:
def function_4(sc):
    '''
    sc: a QuantumCircuit that calculates a Simon's oracle for a given b
    returns:
     b represented as string of length 4
    '''
    ### your code here
    return '0000'

Use the following cell to test your code.

In [160]:
#TEST_CELL don't remove this comment
b = "0101"
sc = simon_oracle(b)
b_calculated = function_4(sc)
print(b_calculated)
b == b_calculated

{'0000': 2499, '1111': 2586, '0101': 2508, '1000': 2498, '0010': 2474, '0111': 2574, '1101': 2454, '1010': 2407}
0.12495
0.1293
0.1254
0.1249
0.1237
0.1287
0.1227
0.12035
1010


False

In [131]:
def test4():
    for x in range(1, 16):
        bin_val = list(bin(x))
        bin_val = (6 - len(bin_val))*['0'] + bin_val[2:]
        b = ''.join(bin_val)
        sc = simon_oracle(b)
        b_calculated = function_4(sc)
        if b != b_calculated:
            print(b, b_calculated)
            return False
    return True
test4()

{'0010': 521, '0100': 482, '0110': 501, '1010': 520, '0000': 500, '1100': 553, '1110': 510, '1000': 509}
0.5087890625
0.470703125
0.4892578125
0.5078125
0.48828125
0.5400390625
0.498046875
0.4970703125
0001 0100


False